name: 🏹 Update Master (PR)

on:
  workflow_dispatch:

jobs:
  update_master_and_create_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: edge
          fetch-depth: 0

      - name: Create Pull Request
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.BOT_TOKEN }}
          script: |
            const { data: pullRequest } = await github.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: "chore: update master",
              head: "edge",
              base: "master",
              body: `
                This PR was created automatically to update master from edge.

                Please approve and squash-merge it.

                IMPORTANT:
                Before merging, make sure all the changes are listed in the squash-commit footer.
                Format must be plain conventional-commit, one per line.
                No \`*\` bullets and no \`----\` comments are allowed.

                Commit footer format for release-please (see https://github.com/googleapis/release-please/tree/main?tab=readme-ov-file#what-if-my-pr-contains-multiple-fixes-or-features):
              `,
            });
            console.log(`Created pull request: ${pullRequest.html_url}`);
